import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import { Josefin_Sans } from "next/font/google"
import Footer from "@/components/Footer";


const roboto = Josefin_Sans({subsets:['latin'], weight:["100","300","400"]})

export const metadata: Metadata = {
  // title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/images/logo-removebg.png", // Adjust the path to match your project
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={` ${roboto.className} overflow-x-hidden w-screen h-full `}>
        <Header />
        <main>
          {children}
        </main>
        <Footer/>
      </body>
    </html>
  );
}
