import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import { Josefin_Sans } from "next/font/google"

const roboto = Josefin_Sans({subsets:['latin'], weight:["100","300","400"]})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={` ${roboto.className} overflow-x-hidden w-screen min-h-screen `}>
        <Header />
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
